
# Communication 
## Communication within the lab


### My doors

### Ways to get ahold of Mason

Here are my secret [Calendly links](https://calendly.com/smasongarrison/).




###  Lab Meetings

Lab members participate in both regular and ad hoc meetings. These meetings may involve everyone or just subgroups. If you have been asked to participate in a meeting, it is because you are a vital part of that project group. If you cannot attend, you should tell the group leader in advance. Remember, however, that the group may no longer be able to carry out the intended work without your presence, so skip meetings sparingly. 

If you do not appear at a meeting as expected and have not informed anyone in advance, it will be assumed that you have been abducted by aliens, and a search-and-rescue mission will be organized. I will draw [inspiration](https://www.nbcnews.com/news/world/how-swedish-professor-helped-rescue-grad-student-isis-controlled-iraq-n947866) from Prof. Charlotta Turner of Lund University.

All meetings begin and end on time, if not earlier. Don't be afraid to remind me of this if/when I am the offending party. It is important that we all respect each other's time.




### Wiki

The lab wiki is our shared collection of knowledge about how to get things done in the lab. The lab handbook you are reading now is "top down", in that I am writing the whole thing myself. By contrast the wiki is a shared resource to which everyone can—and should—contribute. A good rule of thumb is that if you need to figure out how to do something, someone else in the lab may someday need to do the same thing. Whenever possible please document what you figure out on the wiki, including updating old sections which may no longer be relevant. Please encourage each other (and those working with you) to do the same! (And me, please remind me!)



### Email

### Calendars


## Communication outside the lab

This section concerns general suggests and wisdom in communication. In the practical science section, I've included rmarkdown templates and practical advice.

### Social Media
### Presentations
#### Talks
#### Posters

### Manuscripts

## Conferences

Conferences are excellent opportunities to present your research, make connections, and learn about new research and methods from others. If possible, I recommend attending two or more conferences while you are a graduate student at Wake Forest and presenting your research at one or more of the conferences you attend.  

Here are some conferences that are worth considering

### ARP

Association for Research in Personality ( https://www.personality-arp.org/ )



### BGA

Behavior Genetics Association ( http://bga.org/ )

Submission Deadline General: Submissions are typically due in March

- Prior Specific Deadlines

Conference Data General: Conference is generally in June

- Specific Example

Typical Costs


### Dev Methods

Developmental Methods ( http://www.developmentalmethods.org/ )

Submission Deadline General

- Prior Specific Deadlines

Conference Date General

- Specific Example

Typical Costs


### ISIR

International Society for Intelligence Research ( https://isironline.org/ )

Submission Deadline General

- Prior Specific Deadlines

Conference Date General

- Specific Example

Typical Costs

### SMEP


Society for Multivariate Experimental Psychology ( https://smep.org/ )

Submission Deadline General

- Prior Specific Deadlines

Conference Data General

- Specific Example

Typical Costs

### Annual Meeting of the Society for Personality and Social Psychology (SPSP)

Sponsoring Organization: Society for Personality and Social Psychology ( http://meeting.spsp.org/ )

Submission Deadline General: Submissions are typically due in July

- Prior Specific Deadlines

Conference Data General: Conference is generally in Winter (Ranges from Late Jan to Early Feb)

- Specific Example

Typical Costs:

### SSSP

Society for Southeastern Social Psychology ( http://southeast.spsp.org/upcoming-and-past-meetings )
Submission Deadline General

- Prior Specific Deadlines

Conference Data General

- Specific Example

Typical Costs


### Name ( Abbreviation )

Sponsoring Organization ( URL )

Submission Deadline General

- Prior Specific Deadlines

Conference Data General

- Specific Example

Typical Costs
