# (PART) Resources {-}

```{r include = FALSE}
source("common.R")

# install.packages("devtools")

if (!require("tweetrmd"))  devtools::install_github("gadenbuie/tweetrmd")
library(tweetrmd) #... embedding tweets

```


# Academic Career Resources

This project gathers together all the resources I've gathered throughout my career. The collections are currently divided into Graduate School Applications and Academic Job Search. Clearly, there's much to add in between those two stages, such as graduate school, fellowships, and the like. 



# Useful Articles

 - [Edyburn, Dave (August 21, 2020). [An Onboarding Guide for Postdoctoral Researchers. Inside Higher Ed](https://www.insidehighered.com/advice/2020/08/21/advice-postdocs-during-start-phase-their-appointments-opinion)
 



# Quantitative Methods Psych Jobs 
<!-- https://osf.io/nhmuv/wiki/home/?edit&view&menu -->
## Motivation

I had a tough time finding examples of job materials for quantitatively-inclined candidates. Here are representative examples from my own materials. Hopefully, they'll be able to help inspire your own materials. In addition, I've added some of the other resources and information that I found helpful. Although this collection has focused on academic jobs, I also considered industry jobs in my search.


## Resources
This is an incomplete list. Suggestions are very much encouraged.

### General Advice

- The Professor Is In: [Blog](http://theprofessorisin.com/) and [Book](https://smile.amazon.com/gp/product/0553419420)

- American Psychological Association [APA Career Resources](https://www.apa.org/careers/resources/academic/)

### Materials

#### Cover letter
- [How To Write Academic Job Cover Letters from The Professor Is In](https://theprofessorisin.com/category/how-to-write-academic-job-cover-letters/)

#### Teaching Statements
- [Vanderbilt Center for Teaching on Teaching Statements]( https://cft.vanderbilt.edu/guides-sub-pages/teaching-statements/)
- [Writing a Teaching Philosophy Statement by Helen G. Grundman](http://www.ams.org/notices/200611/comm-grundman.pdf)
- [University of Arizona on Writing Diversity Statements](https://postdoc.arizona.edu/content/writing-diversity-statements)

#### Research Statements

#### Diversity Statements
- [The Effective Diversity Statement from InsideHigherEd](https://www.insidehighered.com/advice/2016/06/10/how-write-effective-diversity-statement-essay)
- [Beck, S. L., (2018). Developing and writing a diversity statement. Vanderbilt University Center for Teaching](https://cft.vanderbilt.edu/guides-sub-pages/developing-and-writing-a-diversity-statement/)

#### Example Materials

- UCSF [Samples for Academic Positions](https://career.ucsf.edu/grad-students-postdocs/career-planning/academic-jobs/applying/academic-samples)
- [Plasticity in Neurodevelopment Lab](https://www.plasticityinneurodevelopmentlab.com/for-academics)
- Mine


## Finding Jobs

### Academic
- [APA PsychCareers](https://www.psyccareers.com/search)
- [APS Employment Network](https://jobs.psychologicalscience.org/)
- [HigherEd Jobs](https://www.higheredjobs.com/faculty/search.cfm?JobCat=91)
- [Psych Jobs Wiki](http://psychjobsearch.wikidot.com/)
- [SMEP Job Postings](https://smep.org/resources/positions-available)
- [Society for Math Psych](http://www.mathpsych.org/index.php?option=com_content&view=category&layout=blog&id=34&Itemid=62)
- [SPSP](https://my.spsp.org/Careers/Job-Search)
- [Times Higher Education](https://www.timeshighereducation.com/unijobs/en-us/listings/psychology/)

### Industry
Most data-savvy companies have a careers page. I've included some of those pages here of companies I applied to, were recruited by, or would be interested in working for. There are also job boards, which companies post positions on. There's some overlap, but not 100%.

#### Specific Companies
- [23andMe](https://www.23andme.com/careers/)
- [ACT](https://careers-act.icims.com/jobs/)
- [Amazon](https://www.amazon.jobs/en/job_categories/data-science)
- [Ancestry](https://careers.ancestry.com/us/en)
- [ETS](https://www.ets.org/careers)
- [Facebook](https://www.facebook.com/careers/jobs)
- [Google](https://careers.google.com/)
- [Houghton Mifflin Harcourt](https://careers.hmhco.com/key/educational-measurement-jobs.html)
- [ITHAKA (JSTOR, Ithaka S+R, Portico)](https://www.ithaka.org/career-opportunities)
- [New York Times](https://www.nytco.com/careers/)
- [Pearson](https://pearson.jobs/)
- [Pew Research Center](https://jobs-prc.icims.com/jobs/)
- [RAND](https://www.rand.org/jobs.html)
- [SSRS](https://ssrs.com/careers/)
- [W. W. Norton & Company](https://wwnorton.com/careers/current-openings)

#### Job Postings
- [Glassdoor](https://www.glassdoor.com)
- [Indeed](https://www.indeed.com/)
- [USA Jobs (US Government Jobs)](https://www.usajobs.gov/)


## Data / Research

- Bureau of Labor Statistics on [STEM crisis or STEM surplus? Yes and yes](https://www.bls.gov/opub/mlr/2015/article/stem-crisis-or-stem-surplus-yes-and-yes.htm)
- [What are the chances of becoming a Psychology Professor?](http://geekpsychologist.com/what-are-the-chances-of-becoming-a-psychology-professor/stem-surplus-yes-and-yes.htm)
    -[(archived link)](http://webcache.googleusercontent.com/search?q=cache:M-P4L1Xj8XoJ:geekpsychologist.com/what-are-the-chances-of-becoming-a-psychology-professor/&hl=en&gl=us&strip=0&vwsrc=0)
- [Boysen, G. A., Morton, J., & Nieves, T. (2019). Kisses of Death in the Psychology Faculty Hiring Process. Teaching of Psychology](https://journals.sagepub.com/doi/abs/10.1177/0098628319853942)
- [Boysen, G. A., Jones, C., Kaltwasser, R., & Thompson, E. (2018). Keys to a successful job talk: Perceptions of psychology faculty. Teaching of Psychology, 45(3), 270-277.](https://journals.sagepub.com/doi/full/10.1177/0098628318779277)
- [Pennycook, G. & Thompson, V. A. (2018). An analysis of the Canadian cognitive psychology job market (2006-2016). Canadian Journal of Experimental Psychology, 72, 71-80.](https://psyarxiv.com/mxa35)
- Washington Post on [The academic job market is a nightmare](https://www.washingtonpost.com/outlook/2019/04/15/job-market-academics-is-nightmare-heres-one-way-fix-it/)
- Jeremy Yoder on [I Found a Tenure-Track Job. Here's What it Took](https://chroniclevitae.com/news/1775-i-found-a-tenure-track-job-here-s-what-it-took)
