# Graduate Student Professional Development

### General Timeline

The timeline below is intended to help you structure your time during the WFU graduate program -- to stay on track with: 
- non-coursework program requirements, 
- professional development opportunities (conferences), and 
- PhD applications, if you plan to apply. 

It likely not comprehensive for your unique situation, and it is expected that you will personalize it. This timeline was originally written by [The AMAZING Shannon Brady](https://psychology.wfu.edu/about-the-department/faculty-and-staff/shannon-brady/). I've tweaked it and added to it. But she really deserves credit for it.

#### Year 1

August

- Match with Advisor
- Consider Submitting to SSSP


September

- Acclimate! Get lab key
- Discuss interests and goals with advisor; personalize timeline


October

- Read relevant literature
- Review Grad Handbook sections for Year 1 
- Begin to develop First Year Project (FYP)
- Consider attending SSSP 


November

- Read relevant literature
- Present FYP to peers; get feedback


December

- Read relevant literature
- Refine plan for FYP
- If needed: Secure IRB approval for FYP 
    - (In my lab needing IRB approval is rare)


January

- Begin data collection OR begin data cleaning/analysis


February

- Collect data and/or clean and analyze data


March

- Collect data and/or clean and analyze data
- Discuss initial ideas for MAP w/ advisor
- Find template for FYP poster; 
    -  discuss w/ advisor
- Consider submitting FYP to BGA

April

- Create and revise FYP poster
- Present FYP Poster


May

- Review Grad Handbook sections for Year 2 
- Discuss initial ideas for MAP w/ advisor
- Generate initial list of PhD topics/advisors; 
    - discuss w/ mentors 
- Consider submitting to a conference (like SPSP)



June

- Identify articles to be "mentor texts"
- Draft Methods section of MAP; get feedback
- Read papers by prospective advisors

July

- Draft Results section of MAP; get feedback
- Read papers by prospective advisors
- Create/update CV
- Consider submitting to SPSP


#### Year 2

August

- Review Grad Handbook expectations for MAP
- Create complete outline of MAP
    - get feedback
- Submit MAP outline and annotated biblio
- Refine list of PhD advisors; 
    - reach out
- Write crappy first draft of SOP
- Consider submitting to SSSP


September

- Schedule MAP feedback meeting
- Send MAP to all committee members
- Contact letter writers
- Discuss SOP with mentors/peers/friends

October

- Have MAP feedback meeting
    - If needed: revise MAP
- Review Grad Handbook expectations for thesis
- Finalize thesis idea
- Review and revise SOP;
- draft any other materials needed for applications
- Send materials to letter writers
- Consider attending SSSP


November

- Draft thesis prospectus; get feedback; revise
- Schedule thesis prospectus mtg 
- If needed, identify new “mentor texts” 
- Get feedback on other materials; finalize
- Submit applications (if due this early)



December

- Have thesis prospectus mtg 
- If needed: Secure IRB approval for thesis
- Draft/refine thesis timeline
- Submit applications



January

- File intent to graduate
- At latest: Begin data collection OR begin data cleaning/analysis
- Find, contact, and confirm outside member for thesis committee
- Maybe: interview(s)



February

- Collect data and/or clean and analyze data 


March

- If needed: revise thesis timeline
- Collect data and/or clean and analyze data 
- Schedule thesis defense
- Revise prospectus into thesis draft
- Submit format thesis to Grad Office
- Maybe: interview(s)



April

- Write, write, write!
- Get feedback and revise
- Defend thesis 
- Submit thesis 
- Complete graduation logistics
- Hopefully: Choose PhD program; inform all programs of decision 


May

- Graduate!
- Organize and annotate all research files
- Make sure advisor has copy of all research files (materials, data, code, notes, etc.) 



June

- Write/revise projects for publication

July

- Write/revise projects for publication; submit


### Graduation Requirement Checklist

https://graduate.wfu.edu/graduation-requirement-checklist-reynolda-campus/
